name: SecureStorage Push Workflow

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  assemble:
    name: AssembleDebug SecureStorage
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: AssembleDebug SecureStorage
        run: bash ./gradlew assembleDebug --stacktrace