name: SecureStorage Tag Workflow

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  assemble:
    name: AssembleDebug SecureStorage
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: AssembleDebug SecureStorage
        run: bash ./gradlew assembleDebug --stacktrace

  test:
    needs: assemble
    name: Test SecureStorage
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [21, 22, 23, 25, 29]
        target: [default]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test SecureStorage
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest --stacktrace

  publish:
    needs: [assemble, test]
    name: Publish SecureStorage
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish SecureStorage
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_USERNAME: andev
        run: bash .buildscripts/build-and-deploy-snapshot.sh